# -*- coding: utf-8 -*-
"""divide2num.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19G10h_JMbGmS3S_03zFZHv5RMbSe8G6H
"""

#Divide two numbers

def divide(x,y):
    result=x/y
    return result

num1 = 30
num2 = 3
result = divide(num1, num2)
print(f"The result of dividing {num1} and {num2} is: {result}")