# -*- coding: utf-8 -*-
"""factorial2num.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19G10h_JMbGmS3S_03zFZHv5RMbSe8G6H
"""

# Factorial Of Two Numbers

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n-1)


number = 5
result = factorial(number)
print(f"The factorial of {number} is: {result}")