# -*- coding: utf-8 -*-
"""multiply2num.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19G10h_JMbGmS3S_03zFZHv5RMbSe8G6H
"""

# Multiply two numbers

def multiply(x, y):
    result = x * y
    return result

# Example usage:
num1 = 5
num2 = 7
result = multiply(num1, num2)
print(f"The result of multiplying {num1} and {num2} is: {result}")